### ISSUE TITLE
chmod: cannot access '/var/vcap/jobs/cassandra/config/certs/ssl_env.ctl': No such file or directory 

### ISSUE THREAD

**Issue by ghost** [orange-cloudfoundry/cassandra-deployment#3] opened 2019-05-14 03:16 UTC
We deployed cassendra using orange-cloudfoundry/cassandra-deployment repo with cassendra-boshrelease of tag v9.
one of cassandra-seeds vm is in failing state.
we have logs that are as :-

chmod: cannot access '/var/vcap/jobs/cassandra/config/certs/ssl_env.ctl': No such file or directory

**Comment by lordcf** [comment] 2019-05-14 05:05
found solution

**Comment by ghost** [comment] 2019-05-14 12:00
Any suggestions on this.

**Comment by OMI69-orange** [comment] 2019-05-14 12:56
this is very strange. In just one seed. If there is something wrong with this release, the error should be propagated on each seeds'node.
How many nodes of type seeds did you create ? 
It's possible to have a look on your logs files (including the deployment manifest)?
regards

**Comment by ghost** [comment] 2019-05-15 04:50
Thanks for reply , we have created 3 instances of seed.
Log file cassandra.err.log shows below error:-

chmod: cannot access '/var/vcap/jobs/cassandra/config/certs/ssl_env.ctl': No such file or directory

Deployment manifest is same as cassendra.yml in cassendra deployment repo, just we did some changes using ops file. ops file attached here.
[ops_file_cassenrda.txt](https://github.com/orange-cloudfoundry/cassandra-deployment/files/3180950/ops_file_cassenrda.txt)

**Comment by OMI69-orange** [comment] 2019-05-15 15:01
Hi,
i see that you'r using the cassandra version 9.
It's quit old. 
I have try to reproduce the deployment with the lastst version v12 and it's work well.
Could you, please, retry with this one : https://github.com/orange-cloudfoundry/cassandra-boshrelease/archive/v12.tar.gz     instead.
PS : here the link to the release v12 : https://github.com/orange-cloudfoundry/cassandra-boshrelease )

Regards.

**Comment by ghost** [comment] 2019-05-16 08:12
Hi @OMI69-orange .
I was going through the release 12 but i am not able to see ssl_env.ctl and gen_keystore_client.sh file in relelase 12(https://github.com/orange-cloudfoundry/cassandra-boshrelease/blob/a8d6220d2126fdeb5f36296dc778b236deb3574e/jobs/cassandra/templates/helpers/ctl_setup.sh#L56
https://github.com/orange-cloudfoundry/cassandra-boshrelease/blob/a8d6220d2126fdeb5f36296dc778b236deb3574e/jobs/cassandra/templates/helpers/ctl_setup.sh#L57).

i think. this file does not exist thats why i am getting error.
correct me i am referring right files or not.

**Comment by OMI69-orange** [comment] 2019-05-16 09:49
Hi @lordcf
you'r right. It's seems that there is no longer need of this file (line 56 and 57 of ctl_setup.sh. But, it's strange thats we don't have this error in our environnement. I have to check it more deeper.

**Comment by ghost** [comment] 2019-05-20 12:05
Hi,
after commenting this two lines and deploy, postdeploy script failed with error.

Error: Action Failed get_task: Task ## result: 1 of 1 post-deploy scripts failed. Failed Jobs: cassandra.

At the time of debugging this error , we got below error after executing post-script file:
INFO: current node '###' is not lowest ID of all UP nodes (i.e. '5###') according to 'nodetool'. Aborting the 'post-deploy' execution on this node.

I try to debug following lines and its returning this id.
./nodetool info   | awk -F: '/^ID/{print $2}'| tr -d ' '  
gives below output
ba87fd37-1c38-45a4-9f96-d596080315fb 

Next line returning following id.
./nodetool status | grep "^U[NLJM] " | sort -k7 | head -n1 | awk '{print $7} '
 it gives below output
52d0e49c-6005-49ba-8562-82d0b3ed7e47 

 
./nodetool status  shows below output
Datacenter: DC1
Status=Up/Down
|/ State=Normal/Leaving/Joining/Moving
--  Address      Load       Tokens       Owns (effective)  Host ID                               Rack
UN  xxxx 69.93 KiB  256          69.8%             52d0e49c-6005-49ba-8562-82d0b3ed7e47  RAC2
UN  xxxx  103.66 KiB  256          67.2%             e640f190-4874-433a-b32a-c553bad21bf9  RAC1
UN  xxxx  69.89 KiB  256          63.0%             ba87fd37-1c38-45a4-9f96-d596080315fb  RAC3

i think. post script failing because bosh returning with diff ids. do i am missing anything.

**Comment by OMI69-orange** [comment] 2019-05-21 07:18
hi,
this this just an informative warning. Because, with bosh we are not sur to be the first node deploy. So we use this method to determine if the password had been already modify by an another node. In this case the post-script failed for some nodes but the cluster is up an running and the and.
regards.

**Comment by OMI69-orange** [comment] 2019-05-21 07:35
adding a code explanation of post-deploy's script :
if [[ $node_id != $up_node_with_lowest_id ]]; then
    echo "INFO: current node '$node_id' is not lowest ID of all UP nodes" \
        "(i.e. '$up_node_with_lowest_id') according to 'nodetool'." \
        "Aborting the 'post-deploy' execution on this node."
    exit 0  <======HERE the explanation of the warning <================
fi

**Comment by ghost** [comment] 2019-05-28 12:03
@OMI69-orange : hi
i have commented the two above lines and created the dev release of 12.
then I deploy Cassandra node and broker and broker is failing with error "Provided username admin and/or password are incorrect".

after I try to login using cqlsh with following command.
cqlsh 10.2.2.102 --cqlversion="3.4.4" -u admin -p testpassword

but this too throwing error:
error:- Connection error: ('Unable to connect to any servers', {'IP': AuthenticationFailed(u'Failed to authenticate to IP: code=0100 [Bad credentials] message="Provided username admin and/or password are incorrect"',)}) .

Even I have try to get older password from this ref: https://github.com/orange-cloudfoundry/cassandra-boshrelease/blob/master/jobs/cassandra/templates/bin/post-deploy.sh#L86.
but not able to see any password on this location.

I think there is an some mismatch on post-deploy script. any suggestion for troubleshooting steps for which password configure?

**Comment by OMI69-orange** [comment] 2019-05-28 12:18
@lordcf : hi
in our environment, we us something call 'credhub' to generate cassandra password. The password is then put inside '.cqlshrc' file. Then to connect onto C* we just need to use the cqlsh.sh script under 'admin_job_tool' job. And then we just run ./cqlsh command and that all.
Concerning the broker part, i think that you are using the classical 'cqlsh' file. So may be, you can try with the job mentionned above.
Please try it and let me know if you can connect to C* cluster.
Regards

PS: the 'admin tool jobs' was added to separated admin'users from lamba's users.

**Comment by lordcf** [comment] 2019-05-29 06:20
@OMI69-orange : we have also use the credhub. i run the ./cqlsh file and its giving following error.
![Screen Shot 05-29-19 at 11 46 AM](https://user-images.githubusercontent.com/25821409/58534058-d9aebc00-8207-11e9-8ed3-eddff41a2e96.PNG)

**Comment by ghost** [comment] 2019-05-29 09:59
@OMI69-orange : actually i have use the ubuntu-trusty stemcell and thats why its was failing with openssl incompatible version.
I have changed to light-bosh-stemcell-315.34-aws-xen-hvm-ubuntu-xenial-go_agent and then admin tool is working fine.

**Comment by OMI69-orange** [comment] 2019-05-29 10:05
@lordcf: ok perfect. We are using stemcell Ubuntu Xenial. That why we embendded python 2.7 in the release because it don't work with version 3 of Python.
Regards

**Comment by OMI69-orange** [comment] 2019-05-29 10:09
@lordcf : I close the issue.

**Closed as completed by OMI69-orange** 2019-05-29 10:09 UTC

**Comment by ghost** [comment] 2019-05-29 11:11
@OMI69-orange : yes. thanks for help and still there is an doubt that how your deployment smoothe without commenting this lines "see ssl_env.ctl" and "gen_keystore_client.sh" .
